
1. Write a NumPy program to get the numpy version and show numpy build configuration.

Level: Easy
In [1]:

import numpy as np

print(np.version.version)
print(np.__config__)

1.18.1
<module 'numpy.__config__' from 'C:\\Users\\CodeLover\\Anaconda3\\lib\\site-packages\\numpy\\__config__.py'>

2. Create a null vector of size 10 but the fifth value which is 1.

Level: Easy
In [2]:

ten_zeroes = np.zeros(10)
ten_zeroes[4] = 1
print(ten_zeroes)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Create a vector with values ranging from 10 to 49.

Level: Easy
In [4]:

ten_fortynine = np.arange(10,50)
print(ten_fortynine)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3. create two arrays and stack them vertically

Level: Easy
4. Reverse a vector (first element becomes last).

Level: Easy
5. Create a 3x3 matrix with values ranging from 0 to 8

Level: Easy
6. Find indices of non-zero elements from [1,2,0,0,4,0]

Level: Easy
7. Create a 10x10 array with random values and find the minimum and maximum values.

Level: Easy
8. Create a random vector of size 30 and find the mean value.

Level: Medium
9. Create a 2d array with 1 on the border and 0 inside

Level: Medium
In [3]:

oneborder = np.ones((10,10))
oneborder[1:-1, 1:-1] = 0
print(oneborder)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

10. How to add a border (filled with 0's) around an existing array

Level: Medium
11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

Sample Output:

[[ 0. 0. 0. 0. 0.] [ 1. 0. 0. 0. 0.] [ 0. 2. 0. 0. 0.] [ 0. 0. 3. 0. 0.] [ 0. 0. 0. 4. 0.]]

Level: Medium
12. Create a 5*5 matrix with random values and normalize it.

Level: Medium
13. How to find common values between two arrays

Level: Medium
14. Consider a generator function that generates 10 integers and use it to build an array

Level: Medium
15. Subtract the mean of each row of a matrix

Level: Hard
16. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

Level: Hard
17. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

Level: Hard


1. Write a NumPy program to get the numpy version and show numpy build configuration.

In [3]:
import numpy as np
print(np.version.version)
print(np.__config__)

1.16.5
<module 'numpy.__config__' from 'C:\\Anaconda\\lib\\site-packages\\numpy\\__config__.py'>


2. Create a null vector of size 10 but the fifth value which is 1.

In [4]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Create a vector with values ranging from 10 to 49.

In [8]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3. create two arrays and stack them vertically

In [10]:
ar1 = np.array([1, 2, 3 ,4])
ar2 = np.array([5, 6, 7, 8])

stac = np.vstack((ar1,ar2))
print(stac)

[[1 2 3 4]
 [5 6 7 8]]


4. Reverse a vector (first element becomes last).

In [13]:
ar1 = np.array([1, 2, 3, 4, 5])
ar_reverse = ar1[::-1]
print(ar_reverse)

[5 4 3 2 1]


5. Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
ar = np.arange(0,9).reshape(3,3)
print(ar)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


6. Find indices of non-zero elements from [1,2,0,0,4,0]

In [23]:
ar = np.array([1,2,0,0,4,0])
print(np.nonzero(ar))

(array([0, 1, 4], dtype=int64),)


7. Create a 10x10 array with random values and find the minimum and maximum values.

In [26]:
ar = np.random.randint(0,100,(10,10))
print(ar)
print(ar.max())
print(ar.min())


[[ 9 88  6 29 24 26 34 53 62 77]
 [53 62 87 32 51 99 18 38 94 86]
 [78 93 22 82 73  9 88 54 21 84]
 [94 91 50 49 62  7 94 47 76 54]
 [39 92 37 72 82 56 11 58 57 40]
 [88 87 78 27 32  8 70 50 93  4]
 [ 6 43 95  0 24 90 42 58 86 71]
 [26  2 27 95 66 98 37 58 27 93]
 [37 65 14 42 21 72 54  1 51 81]
 [54 63 45 25 82 81 76 72 17 76]]
99
0


8. Create a random vector of size 30 and find the mean value.

In [35]:
ar = np.random.randint(100,200,size = 30)
print(ar)
print("size = ",ar.size)
print("mean = ",ar.mean())

[114 123 135 174 162 198 117 132 143 195 151 130 120 160 199 193 186 135
 140 130 120 117 185 103 143 174 168 121 120 184]
size =  30
mean =  149.06666666666666


9. Create a 2d array with 1 on the border and 0 inside

In [40]:
ar = np.ones((5,5))
ar[1:-1, 1:-1] = 0
print(ar)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


10. How to add a border (filled with 0's) around an existing array

In [71]:
ar = np.random.randint(0, 30,(5,5))
np.pad(ar,(1,1), mode = 'constant')

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0, 25,  3,  9, 25, 17,  0],
       [ 0,  6,  7, 12, 23,  3,  0],
       [ 0, 25, 16, 18,  8,  6,  0],
       [ 0, 25,  6, 18, 18, 11,  0],
       [ 0,  1, 13, 10, 23, 25,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [74]:
ar = np.zeros((5,5))
ar[1,0]=1
ar[2,1] = 2
ar[3,2] = 3
ar[4,3] = 4
print(ar)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]
