1. Create an array and find sum of it.

In [4]:
import numpy as np
a = np.random.randint(0,100,10)
print(a)
b = np.sum(a)
b

[22 23 83 45 25 17 82 28 90 55]


470

2. Find sin of given array.

In [6]:
a= np.array([0,30,45,60,90])
b = np.sin(a)
b

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

3. Find mean of matrix along row and column.

In [12]:
a = np.random.randint(0,10,(3,3))
print(a)
row = np.mean(a,axis = 1)
print(row)
column = np.mean(a,axis = 0)
print(column)

[[7 2 5]
 [1 5 9]
 [3 8 6]]
[4.66666667 5.         5.66666667]
[3.66666667 5.         6.66666667]


4. Find standard deviation of given array.

In [18]:
print(a)
sd = np.std(a)
sd

[[7 2 5]
 [1 5 9]
 [3 8 6]]


2.5579698740491863

5. Create a 3*3 matrix and print it's transpose matrix

In [19]:
print(a)
a_transpose = a.transpose()
a_transpose

[[7 2 5]
 [1 5 9]
 [3 8 6]]


array([[7, 1, 3],
       [2, 5, 8],
       [5, 9, 6]])

6. Create an array of 3*3 and find index of max along both axis.

In [31]:
print(a)
max_a_col = a.argmax(axis = 0)
max_a_row = a.argmax(axis = 1)
print(max_a_col, max_a_row)

[[ 1 13 10  4 18]
 [ 1  8 12 12 19]
 [10 17  8  7 11]
 [10  7 18  4 12]
 [ 3 13 16  5  8]]
[2 2 3 1 1] [4 4 1 2 2]


7. find sum of two matrix.

In [21]:
print(a)
b = np.random.randint(0,10,(3,3))
print(b)
sum_of_matrix = np.add(a,b)
sum_of_matrix

[[7 2 5]
 [1 5 9]
 [3 8 6]]
[[7 8 2]
 [6 3 9]
 [6 2 4]]


array([[14, 10,  7],
       [ 7,  8, 18],
       [ 9, 10, 10]])

8. Find max element along axis=0 and axis=1.

In [28]:
a = np.random.randint(1,20,(5,5))
print(a)
max_0 = np.max(a,axis = 0)
max_1 = np.max(a,axis = 1)
print(max_0, max_1)

[[ 1 13 10  4 18]
 [ 1  8 12 12 19]
 [10 17  8  7 11]
 [10  7 18  4 12]
 [ 3 13 16  5  8]]
[10 17 18 12 19] [18 19 17 18 16]


9. Write a program to add two arrays of different shape.

In [4]:
import numpy as np
i = np.random.randint(1,20,(5,5))
j = np.array([1,2,3,4,5])
i+ j[:, np.newaxis]

array([[ 6, 17, 11, 13, 17],
       [19, 19,  4, 16, 21],
       [18, 14, 12, 16, 22],
       [12,  8, 19, 23, 13],
       [13, 14, 13, 11, 21]])

10. Try to solve a array and print a array with indices which would sort the given array.

sample input:

a = [3,1,8,2]

output:

[1,3,0,2]

In [5]:
a = np.array([3,1,8,2])
b = np.argsort(a)
b

array([1, 3, 0, 2], dtype=int64)

11. Try to do perform same operation mentioned in previous questions for multidimentional array along both axis.

In [7]:
print(i)
i_row = np.argsort(i, axis = 1)
i_col = np.argsort(i, axis = 0)
print(i_row)
print(i_col)

[[ 5 16 10 12 16]
 [17 17  2 14 19]
 [15 11  9 13 19]
 [ 8  4 15 19  9]
 [ 8  9  8  6 16]]
[[0 2 3 1 4]
 [2 3 0 1 4]
 [2 1 3 0 4]
 [1 0 4 2 3]
 [3 0 2 1 4]]
[[0 3 1 4 3]
 [3 4 4 0 0]
 [4 2 2 2 4]
 [2 0 0 1 1]
 [1 1 3 3 2]]


12. calculate multiplication of transpose and matrix itself of a 3*3 matrix.

In [9]:
a = np.random.randint(1,10,(3,3))
print(a)
print(b)
b = np.transpose(a)
a*b

[[4 4 3]
 [3 1 2]
 [6 8 5]]
[[4 3 1]
 [1 5 3]
 [3 1 5]]


array([[16, 12, 18],
       [12,  1, 16],
       [18, 16, 25]])

13. Find solution for given linear equstion:

2x + 5y = 28 4x + 3*y = 81


In [10]:
a = np.array([[2,5],[4,3]])
b = np.array([28, 81])
np.linalg.solve(a,b)

array([22.92857143, -3.57142857])

14. Find Rank, Trace, Inverse, Determinant of a given matrix.

A=[[1, 1, 1], [2, 2, 2], [3, 3, 3]])

In [17]:
A=np.array([[1, 6, 3], [2, 8, 3], [3, 9, 1]])
print(A)
print("rank = ", np.linalg.matrix_rank(A))
print("trace = ", np.trace(A))
print(" inverse = ", np.linalg.inv(A))
print("Determinant = ", np.linalg.det(A))

[[1 6 3]
 [2 8 3]
 [3 9 1]]
rank =  3
trace =  10
 inverse =  [[-3.8  4.2 -1.2]
 [ 1.4 -1.6  0.6]
 [-1.2  1.8 -0.8]]
Determinant =  4.999999999999998


15. Find cube of a mtrix.

In [18]:
print(A)
np.linalg.matrix_power(A, 3)

[[1 6 3]
 [2 8 3]
 [3 9 1]]


array([[ 256,  996,  333],
       [ 332, 1283,  423],
       [ 333, 1269,  406]])