1. Find dot product of two arrays.

a = [2j, 3j],

b = [2j, 3j]

In [2]:
import numpy as np
a = np.array([2, 3])
b = np.array([3, 4])
c = np.dot(a,b)
c


18

2. Create two arrays of 2-D and find dot product of it.

In [4]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]])
c = np.dot(a,b)
c

array([[37, 40],
       [85, 92]])

3. Find vector product of given array.

In [5]:
a = np.array([1+2j,3+4j])
b = np.array([5+6j,7+8j])
c = np.vdot(a,b)
c

(70-8j)

4. First create given array withound using direct value insted use numpy utlities and then find inner product for given array.

In [6]:
# a = [[ 0 1 2 3] [ 4 5 6 7] [ 8 9 10 11]]
# b = [[12 13 14 15] [16 17 18 19] [20 21 22 23]]


a = np.arange(24).reshape((2,3,4))
print(a)
b = np.arange(4)
print(b)
np.inner(a, b)



[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[0 1 2 3]


array([[ 14,  38,  62],
       [ 86, 110, 134]])

5. Using given two array try to print out 3rd given array.

a = np.array(['a', 'b', 'c'], dtype=object) b = np.array([1,2,3])

output = [['a', 'aa', 'aaa'], ['b', 'bb', 'bbb'], ['c', 'cc', 'ccc']]

In [7]:
a =np.array(['a', 'b', 'c'], dtype=object)
b = np.array([1,2,3])
np.outer(a,b)

array([['a', 'aa', 'aaa'],
       ['b', 'bb', 'bbb'],
       ['c', 'cc', 'ccc']], dtype=object)

6. Solve the system of equations 3 x0 + x1 = 9 and x0 + 2 x1 = 8

In [12]:
a = np.array([[3,1],[1,2]])
b = np.array([9,8])
np.linalg.solve(a,b)

array([2., 3.])

7. Check the following solution is right or wrong uisng numpy utilities.

2x+3y=8 3x+y=5

solution: x=1 , y=2

In [13]:
a = np.array([[2,3],[3,1]])
b = np.array([8,5])
x = np.array([1,2])
np.allclose(np.dot(a, x), b)

True

8. Write a program to add two arrays of different shape.

In [15]:
a=np.array([0.0,10.0,20.0,30.0])
b=np.array([1.0,2.0,3.0])
a[:, np.newaxis]+b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

9. Create a 3 * 3 array find it's diagonal using numpy utilities.

In [16]:
a = np.random.randint(1,10,(3,3))
print(a)
a.diagonal()


[[6 4 5]
 [8 7 2]
 [8 5 9]]


array([6, 7, 9])

10. Now find anti - diagonal in previous question using horizontal and vector flip.

In [17]:
print(a)
print("h_flip:\n",np.fliplr(a).diagonal())
print("v_flip:\n",np.flipud(a).diagonal())


[[6 4 5]
 [8 7 2]
 [8 5 9]]
h_flip:
 [5 7 8]
v_flip:
 [8 7 5]


11. Create given array without using indexing.

a = [[4, 0, 0], [0, 4, 0], [0, 0, 4], [0, 0, 0], [4, 0, 0], [0, 4, 0], [0, 0, 4]]

In [18]:
a = np.zeros((7, 3), int)
np.fill_diagonal(a, 4, wrap=True)
a

array([[4, 0, 0],
       [0, 4, 0],
       [0, 0, 4],
       [0, 0, 0],
       [4, 0, 0],
       [0, 4, 0],
       [0, 0, 4]])