



20. Given a 1d array(size 100) of boolean values, identify total number of True in it.
21. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?


24. Given two random arrays of shape 5X5, identify the common elements between them.


1. Count The Number Of Times Each Value Appears In An Array Of Integers

In [2]:
import numpy as np
a = [1,3,5,2,1,1,8,4,2,4,3,5,5,1]
x = 1
a.count(x)


4

2. Given 9 Integers. You have to convert them into 3*3 Numpy array using Reshape function.

In [6]:
a = np.arange(9).reshape(3,3)
a
print(a, type(a))

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>


3. How to find the memory size of any array

In [8]:
a.size * a.itemsize

72

4. Create a 2d array of size 10 by 10 with 1 on the border and 0 inside.

In [12]:
import numpy as np
a = np.ones((10,10))
a[1:-1,1:-1] =0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.Create a 8x8 matrix and fill it with a checkerboard pattern.

In [4]:
import numpy as np
a = np.zeros((8,8),int)
# a[1::2] = 1
# a[::1] = 1
a[1::2,::2] = 1
a[::2,1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

6. Normalize a 5x5 random matrix.
normalization formula : ((a-mean(a))/std(a))

In [5]:
a = np.random.randint(0,25,(5,5))
print(a)
norma = ((a-np.mean(a))/np.std(a))
print(norma)

[[ 4 23 19 17 12]
 [12 17 14 10 22]
 [ 8  5 18  1  4]
 [21  1  3  9  1]
 [ 5  0  8  9  9]]
[[-0.86827379  1.84508179  1.27384904  0.98823266  0.27419172]
 [ 0.27419172  0.98823266  0.5598081  -0.01142466  1.70227361]
 [-0.29704103 -0.7254656   1.13104085 -1.29669835 -0.86827379]
 [ 1.55946542 -1.29669835 -1.01108197 -0.15423284 -1.29669835]
 [-0.7254656  -1.43950654 -0.29704103 -0.15423284 -0.15423284]]


7. Given a 1D array in range(0,11), negate all elements which are between 3 and 8, in place.

In [8]:
a = np.arange(0,11)
print(a)
neg_a = np.negative(a[4:8])
print(neg_a)

[ 0  1  2  3  4  5  6  7  8  9 10]
[-4 -5 -6 -7]


8. How to get the dates of yesterday, today and tomorrow?

In [10]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1,'D')
print(yesterday)
Today = np.datetime64('today')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(Today, tomorrow)

2020-03-22
2020-03-23 2020-03-24


9. Generate two arrays of size 2X4 & 3X3, find difference between them.

10. Given 1d array of ['cat','dog','rat'], genrate 100 elements of 1d array consisting of the above 3 value ?
['cat','cat',...,'rat','dog','dog','cat'...]

In [19]:
import numpy as np
np.choose(np.random.randint(0,3, 10), choices = ['cat', 'dog', 'rat'])


array(['cat', 'rat', 'dog', 'rat', 'cat', 'dog', 'cat', 'dog', 'dog',
       'rat'], dtype='<U3')

11. Create a vector of size 10 with values ranging from 0 to 1, both excluded without manually deducing the values

In [21]:
x = np.linspace(0,1,12,endpoint=True)[1:-1]
x

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

12. Given a two dimensional array, how to extract unique rows?

In [28]:
a = np.array([[1, 1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0],
       [0, 1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0]])
np.unique(a,axis=0)

array([[0, 1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0]])

13. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.

14. How to find the closest value (to a given scalar) in a vector?

In [34]:
a = np.arange(10)
print(a)
x= 7.56
index = (np.abs(a-x)).argmin()
print(a[index])

[0 1 2 3 4 5 6 7 8 9]
8


15. Consider a random vector with shape (10,2) representing coordinates, find point by point distances. Use euclidian distance.

In [39]:
from scipy.spatial import distance
a = np.random.randint(0,100,(10))
b = np.random.randint(0,100,(10))
print(a)
print(b)
d = distance.euclidean(a, b)
print(d)

[60  4 34 28 82 34 40 72 31 29]
[39 71 42 33 88 60 38 75 56 12]
81.59656855530139


16. How to sort an array by the nth column?

In [46]:
x = np.random.randint(1,25,(5,5))
print(x)
arr = x[x[:,3].argsort()]
print(arr)

[[ 4  5 17 15 20]
 [ 1 22  4  2 20]
 [14  8  3 13 22]
 [21  8  5  7  2]
 [ 4 12 22 22  5]]
[[ 1 22  4  2 20]
 [21  8  5  7  2]
 [14  8  3 13 22]
 [ 4  5 17 15 20]
 [ 4 12 22 22  5]]


17.How to tell if a given 2D array has null columns?

In [56]:
a = np.array([[1,2,3],[0,0,0], [6,5,9]])
print((~a.any(axis=0)).any())

False


18. Considering a two dimensions array, how to get sum over the last two columns at once?

19. Given a 2d array of 5X5, increment 1st column by 1, second column by 2, 3rd column by 3 & so on till the last column

In [91]:
a = np.arange(25).reshape(5,5)
# print(a)
a[:,1]+1
a[:,2]+2
a[:,3]+3
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

23. How to get n largest value of an array?

In [87]:
a = np.arange(25).reshape(5,5)
np.max(a)

24

22. How to swap two rows of an array?

In [96]:

a[[0, 2]] = a[[2, 0]]
a
# print(a[0,2])

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])